name = "greyscript"
scope = "source.greyscript"
grammar = "miniscript"
line_comments = ["//"]
block_comment = ["/*", "*/"]
# path_suffixes = ["src"]
file_types = ["gs", "ms", "src"]

#[[language_servers]]
#name = "greybel-languageserver"
