id = "greyscript"
name = "Greyscript"
version = "0.1.0"
schema_version = 1
authors = ["stddebugprint"]
description = "Greyscript language support for Zed"
repository = "https://github.com/stddebugprint/greyscript-zed"

[language_servers.greybel-languageserver]
name = "Greybel Language Server"
languages = ["greyscript"]

[grammars.miniscript]
repository = "https://github.com/ayecue/tree-sitter-miniscript"
commit = "361b87bf451ff7879d78ba45ffa3fcd32540a271"
